# Generated by Django 4.2.5 on 2024-02-22 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Men_latest',
        ),
    ]
