# Generated by Django 4.2.5 on 2024-03-01 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='men_latest',
            name='price',
        ),
        migrations.CreateModel(
            name='expanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapps.men_latest')),
            ],
        ),
    ]
